[package]
name = "cpft"
version = "0.6.1"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
const_format = "0.2.35"
eframe = { version = "0.34.1", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "glow",
    "persistence",
    "wayland",
] }
egui = "0.34.1"
egui-phosphor = "0.12.0"
egui_dnd = "0.15.0"
egui_double_slider = "1.1.0"
egui_extras = "0.34.1"
egui_plot = "0.35.0"
egui_table = "0.8.0"
egui_tiles = "0.15.0"
indexmap = "2.14.0"
itertools = "0.14.0"
log = "0.4.29"
nalgebra = "0.34.2"
polars = { git = "https://github.com/pola-rs/polars", rev = "bf6a425", default-features = false, features = [
    "abs",
    "array_arithmetic",
    "bitwise",
    "cov",
    "cross_join",
    "diagonal_concat",
    "dtype-array",
    "dtype-decimal",
    "dtype-i16",
    "dtype-i8",
    "dtype-struct",
    "dtype-u16",
    "dtype-u8",
    "fmt_no_tty",
    "iejoin",
    "interpolate",
    "is_between",
    "lazy",
    "list_eval",
    "meta",
    "rank",
    "round_series",
    "row_hash",
    "serde",
    "sign",
    "trigonometry",
    #
    # "interpolate_by",
    # "ipc",
    # "parquet",
    # "polars-io",
] }
polars-utils = { version = "0.53.0", features = ["nightly"] }
ron = "0.12.1"
scirs2 = "0.4.2"
scirs2-core = { version = "0.4.2", features = ["arrow"] }
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.44"
typed-builder = "0.23.2"
uom = { version = "0.38.0", features = ["serde"] }

# polars_excel_writer = "0.22.0"

egui_ext = { git = "https://github.com/kgv/egui_ext", branch = "0.6.0" }
egui_l20n = { git = "https://github.com/kgv/egui_l20n", branch = "0.5.0", features = [
    "macros",
] }
egui_tiles_ext = { git = "https://github.com/kgv/egui_tiles_ext", branch = "0.3.0" }
lipid = { git = "https://github.com/ippras/lipid", branch = "bf6a425", features = [
    "serde",
] }
metadata = { git = "https://github.com/ippras/metadata", branch = "bf6a425", features = [
    "egui",
    "polars",
] }
polars_ext = { git = "https://github.com/kgv/polars_ext", branch = "bf6a425", features = [
    "array",
    "temporal_conversions",
] }

[dev-dependencies]
ed25519-dalek = "2.2.0"

# native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wasm-bindgen-futures = "0.4.67"
web-sys = "0.3.94"

[features]
default = []
wasm = []

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds
[profile.dev.package."*"]
opt-level = 2
