[package]
name = "cpft"
version = "0.3.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
eframe = { version = "0.33.2", default-features = false, features = [
    "accesskit",
    "default_fonts",
    "glow",
    "persistence",
    "wayland",
] }
egui = "0.33.2"
egui-phosphor = "0.11.0"
egui_dnd = "0.14.0"
egui_extras = "0.33.2"
egui_plot = "0.34.0"
egui_table = "0.6.0"
egui_tiles = "0.14.0"
itertools = "0.14.0"
log = "0.4.28"
nalgebra = "0.34.1"
polars = { git = "https://github.com/pola-rs/polars", rev = "fea5335", default-features = false, features = [
    "abs",
    "bitwise",
    "cross_join",
    "diagonal_concat",
    "dtype-array",
    "dtype-decimal",
    "dtype-i16",
    "dtype-i8",
    "dtype-struct",
    "dtype-u16",
    "dtype-u8",
    "fmt_no_tty",
    "iejoin",
    "is_between",
    "lazy",
    "list_eval",
    "polars-io",
    "rank",
    "round_series",
    "row_hash",
    "serde",
    "sign",
    "trigonometry",
    #
    # "ipc",
    # "parquet",
    # "interpolate",
    # "interpolate_by",
] }
polars-utils = { version = "0.52.0", features = ["nightly"] }
ron = "0.12.0"
serde = { version = "1.0.228", features = ["derive"] }
tracing = "0.1.43"
uom = { version = "0.37.0", features = ["serde"] }

egui_ext = { git = "https://github.com/kgv/egui_ext" }
egui_l20n = { git = "https://github.com/kgv/egui_l20n", features = ["macros"] }
egui_tiles_ext = { git = "https://github.com/kgv/egui_tiles_ext" }
lipid = { git = "https://github.com/ippras/lipid", branch = "fea5335", features = [
    "serde",
] }
metadata = { git = "https://github.com/ippras/metadata", branch = "fea5335", features = [
    "egui",
    "polars",
] }
polars_ext = { git = "https://github.com/kgv/polars_ext", branch = "fea5335", features = [
    "temporal_conversions",
] }

# native
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

# web
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
tracing-wasm = "0.2.1"
wasm-bindgen-futures = "0.4.56"
web-sys = "0.3.83"

[profile.release]
opt-level = 2 # fast and small wasm

# Optimize all dependencies even in debug builds
[profile.dev.package."*"]
opt-level = 2
