AbsoluteRetentionTime = Absolute
    .hover = Absolute retention time.
Alpha = Alpha
    .abbreviation = α
    .hover = ?.
Angle = Angle
AscendingOrder = Ascending
    .hover = Direct order (from min to max).
Calculate = Calculate
ChainLength = Chain length
    .hover = ECL, FCL and ECN.
Database = Database
DeadTime = Dead time
    .hover = Dead time.
DeltaDegreesOfFreedom = Delta degrees of freedom
    .abbreviation = DDOF
DeltaDegreesOfFreedom = Delta Degrees of Freedom
    .abbreviation = DDOF
    .hover = The divisor used in calculations is N - DDOF, where N represents the number of elements. By default DDOF is zero.
    .info = Different values of the argument ddof are useful in different contexts.
DeltaRetentionTime = Delta
    .hover = Retention time distance to the nearest saturated fatty acid with a lower retention time.
Derivative = Derivative
    .hover = Derivative calculations.
DescendingOrder = Descending
    .hover = Reverse order (from max to min).
Distance = Distance
    .hover = Euclidean distance.
DistanceSettings = { -gear } Distance settings
EquivalentCarbonNumber = Equivalent carbon number
    .abbreviation = ECN
EquivalentChainLength = Equivalent chain length
    .abbreviation = ECL
EquivalentChainLengthDistance = Equivalent chain length
    .abbreviation = ECL
    .hover = Equivalent chain length distance between two fatty acids.
EuclideanDistance = Euclidean distance
    .abbreviation = d
    .hover = Euclidean distance (in coordinates retention time and equivalent chain length) between two fatty acids.
FattyAcid = Fatty acid
    .abbreviation = FA
Filter = Filter
FilterByFattyAcids = Fatty acids
    .hover = Filter by fatty acids.
FilterByOnsetTemperature = Onset temperature
    .hover = Filter by onset temperature.
FilterByTemperatureStep = Temperature step
    .hover = Filter by temperature step.
FractionalChainLength = Fractional chain length
    .abbreviation = FCL
From = From
Grid = Grid
Horizontal = Horizontal
Identifier = Identifier
    .abbreviation = ID
    .hover = Measurement identifier.
Index = Index
Language = Language
Legend = Legend
LogarithmOfTheRetentionTime = Logarithmic
    .hover = Calculate the equivalent chain length using the logarithms of the retention times.
Mass = Mass
    .hover = Related masses of [RCO]+, [RCOO]-, RCOOH and RCOOCH3.
Maximum = Maximum
    .hover = Maximum.
Mean = Mean
    .hover = Mean.
Median = Median
    .hover = Median.
Minimum = Minimum
    .hover = Minimum.
Mode = Mode
    .hover = Measurement mode: onset temperature and temperature step.
OnsetTemperature = Onset temperature
    .abbreviation = T₀
Order = Order
    .hover = Order by.
PlotView = { -plot } Plot
    .hover = View as plot.
Precision = Precision
    .hover = Round floating points to given decimal numbers.
RadiusOfPoints = Radius of points
    .hover = The radius of all points on the plot.
RelativeFattyAcid = Relative
    .hover = The fatty acid to calculate relative retention time.
RelativeRetentionTime = Relative
    .hover = Relative retention time calculated through the selected fatty acid.
ResetState = Reset
    .hover = Reset state.
ResetApplicatioinState = Reset
    .hover = Reset applicatioin state.
ResizeTableColumns = Resize
    .hover = Resize table columns.
RetentionTime = Retention time
    .abbreviation = RT
    .hover = Retention time (absolute, relative and distance).
RetentionTimeDistance = Retention time
    .abbreviation = RT
    .hover = Retention time distance between two fatty acids.
Sample = Sample
    .hover = Sample.
Significant = Significant
    .hover = Round floating points to a number of significant figures.
Slope = Slope
Sort = Sort
    .hover = Sort by.
SortByAggregation = Aggregation
    .hover = Use an aggregation function to calculate the value to sort.
SortByAlpha = Alpha
    .hover = Sort by alpha distance.
SortByDistance = Distance
    .hover = Use a distance function to calculate the value to sort.
SortByEquivalentChainLengthDistance = Equivalent chain length
    .hover = Sort by equivalent chain length distance.
SortByEuclideanDistance = Euclidean
    .hover = Sort by euclidean distance.
SortByFattyAcids = Fatty acids
    .hover = Sort by fatty acids.
SortByKey = Key
    .hover = Sort by key.
SortByMaximum = Maximum
    .hover = Select the maximum of the values to sort.
SortByMean = Mean
    .hover = Select the mean of the values to sort.
SortByMedian = Median
    .hover = Select the median of the values to sort.
SortByMinimum = Minimum
    .hover = Select the minimum of the values to sort.
SortByRetentionTime = Retention time
    .hover = Sort by equivalent carbon number and retention time.
SortByRetentionTimeDistance = Retention time
    .hover = Sort by retention time distance.
SortByValue = Value
    .hover = Sort by value.
Source = Source
Settings = Settings
    .hover = Settings.
StandardDeviation = Standard deviation
    .hover = Standard deviation.
StickyColumns = Sticky
    .hover = Number of sticky columns.
TableView = { -table } Table
    .hover = View as table.
Tabs = Tabs
Temperature = Temperature
    .abbreviation = T
    .hover = Eluating temperature.
TemperatureStep = Temperature step
    .abbreviation = ΔT
    .hover = Temperature increment per minute.
To = To
TruncateHeaders = Truncate
    .hover = Truncate header text.
Vertical = Vertical

Euclidean = Euclidean
Priority = Priority
CheckAll = Check all
UncheckAll = Uncheck all
